import { createClient } from '@supabase/supabase-js';
import { jsPDF } from "jspdf";

const supabase = createClient('https://itfwpvjscosvofgocvpx.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0ZndwdmpzY29zdm9mZ29jdnB4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MTk1OTI0MSwiZXhwIjoyMDU3NTM1MjQxfQ.mHn_YlA-0q_SAnq2Xw8667iJ00K2Kj81_rD-uM6Ym6s');

export default async function handler(req, res) {
  const { phone } = req.query;
  if (!phone) return res.status(400).send("Phone number is required");

  try {
    const { data: records } = await supabase
      .from('weekly_summaries')
      .select('*')
      .eq('phone_number', phone)
      .order('created_at', { ascending: false });

    const doc = new jsPDF();
    
    // Header Style
    doc.setFillColor(41, 128, 185); // Blue header
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text("WANDATAX BUSINESS STATEMENT", 105, 25, { align: "center" });

    // Business Info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.text(`User Phone: +${phone}`, 20, 55);
    doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 20, 62);
    
    // Table Setup
    let y = 80;
    doc.setFont(undefined, 'bold');
    doc.text("Date", 20, y);
    doc.text("Category", 70, y);
    doc.text("Amount (CFA)", 160, y);
    doc.line(20, y + 2, 190, y + 2);
    
    y += 10;
    doc.setFont(undefined, 'normal');
    let grandTotal = 0;

    records.forEach(r => {
      if (y > 270) { doc.addPage(); y = 20; }
      const dateStr = new Date(r.created_at).toLocaleDateString();
      doc.text(dateStr, 20, y);
      doc.text(r.category || "General", 70, y);
      doc.text(r.turnover.toLocaleString(), 160, y);
      grandTotal += r.turnover;
      y += 10;
    });

    // Totals Section
    y += 10;
    doc.line(20, y, 190, y);
    y += 10;
    doc.setFont(undefined, 'bold');
    doc.text("TOTAL SALES:", 20, y);
    doc.text(`${grandTotal.toLocaleString()} CFA`, 160, y);
    
    y += 8;
    doc.text("TAX RESERVE (5%):", 20, y);
    doc.text(`${(grandTotal * 0.05).toLocaleString()} CFA`, 160, y);

    // Footer
    doc.setFontSize(10);
    doc.setFont(undefined, 'italic');
    doc.text("This is a digital record generated by WandaTax Cameroon.", 105, 285, { align: "center" });

    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=WandaTax_${phone}.pdf`);
    return res.send(pdfBuffer);

  } catch (error) {
    return res.status(500).send("Error generating PDF: " + error.message);
  }
}
